
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME} 
        DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
        imagePullPolicy: Always
        env:
          - name: env
            value: "testing"        
        ports:
        - containerPort: 18080
          name: ${APP_NAME}
          protocol: TCP
        resources:
          limits:
            cpu: 1.5
          requests:
            cpu: 500m
        volumeMounts:
        - name: app-log-volume
          mountPath: /var/log/webDemo/
      volumes:
      - name: app-log-volume
        hostPath:
          # directory location on host
          path: /var/log/k8s-mount/webDemo
      imagePullSecrets: 
      - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  type: NodePort
  ports:
  - name: ${APP_NAME}
    port: 18080
    nodePort: ${HOST_PORT}


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
