
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdemo-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdemo-dev 
  template:
    metadata:
      labels:
        app: webdemo-dev
    spec:
      containers:
      - name: webdemo 
        image: registry.lab.local:5000/webdemo-dev:latest
        imagePullPolicy: Always
        env:
          - name: env
            value: "testing"        
        ports:
        - containerPort: 18080
          name: webdemo-dev
          protocol: TCP
      imagePullSecrets: 
      - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: webdemo-dev 
spec:
  selector:
    app: webdemo-dev 
  type: NodePort
  ports:
  - name: webdemo-dev
    port: 18080
    nodePort: 31235

