
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${appname}
  template:
    metadata:
      labels:
        app: ${appname}
    spec:
      containers:
      - name: ${appname} 
        image: ${IMAGE}:${VERSION}
        imagePullPolicy: Always
        env:
          - name: env
            value: "testing"        
        ports:
        - containerPort: 18080
          name: ${appname}
          protocol: TCP
        resources:
          limits:
            cpu: 1.5
          requests:
            cpu: 500m
        volumeMounts:
        - name: app-log-volume
          mountPath: /var/log/webDemo/
      volumes:
      - name: app-log-volume
        hostPath:
          # directory location on host
          path: /var/log/k8s-mount/webDemo
      imagePullSecrets: 
      - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: ${appname}
spec:
  selector:
    app: ${appname}
  type: NodePort
  ports:
  - name: ${appname}
    port: 18080
    nodePort: 31235


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${appname}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${appname}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
