spring:
   profiles:
      active: '@spring.profiles.active@'
server:
   port: 18080
env:
   name: '@env.name@'

secret:
  password: '@secret.password@'   
   
jasypt:
    encryptor:
      privateKeyFormat: PEM
      privateKeyLocation: file:config/private.key   